name: Run tests

on:
  push:
    paths:
      - '.forgejo/workflows/**/*'
      - 'flake.nix'
      - 'flake.lock'
      - 'options/**/*'
      - 'modules/**/*'
      - 'lib/**/*'
      - 'tests/**/*'

jobs:
  run_tests:
    runs-on: native

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: $ alejandra --check *
        run: |
          nix fmt -- -c *
      
      - name: $ nix flake check
        run: |
          nix run github:Mic92/nix-fast-build -- --skip-cache --no-nom --no-link
